version: "3.3"
services:
  flask:
    image: family_day_out_server
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    container_name: fdo_dev_container
    ports:
      - "5006:5006"
    command: ["python", "-m", "api.app"]
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=True
      - MYSQL_DB_URL=mysql+pymysql://${MYSQL_ROOT_USER}:"${MYSQL_ROOT_PASSWORD}"@mysql:3306/db_family_day_out_planner
  
  mysql:
    image: mysql:8.0.30
    container_name: fdo_mysql_container
    restart: always
    volumes:
      - db_data:/var/lib/mysql:rw
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"

  adminer:
    image: adminer
    restart: always
    ports:
      - "5001:8080"

volumes:
  db_data:
